javascripts:
  app:
    - public/javascripts/jquery.js
    - public/javascripts/jquery_ujs.js
    - public/javascripts/jquery-ui.js
    - public/javascripts/underscore.js
    - public/javascripts/backbone.js
    - public/javascripts/modernizr.js
    - public/javascripts/backbone.localStorage.js
    - public/javascripts/application.js
    - public/javascripts/coffee/*.js
    - app/views/jst/**/*.jst
stylesheets:
  app:
    - public/stylesheets/*.css
